// DO NOT EDIT THIS FILE (config.js), THIS IS CREATED BY GULP TASK
// jshint ignore: start
(function() {
'use strict';

angular.module("firebaseDemo.config", [])

.constant("config", {
  "firebaseUrl": "https://poolit-1bf15.firebaseio.com/"
})

;
})();
